### ISSUE TITLE
Consolidate `cisagov/ansible-role-pip` into this role

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/ansible-role-python#51]
# 💡 Summary #

We should consolidate [cisagov/ansible-role-pip]'s functionality into this role by incorporating it as `install_pip`/`install_pip2` role variables.

## Motivation and context ##

Currently if one uses the [cisagov/ansible-role-pip] role you will get Python packages due to dependencies on the system pip packages. This can lead to inconsistent package installations if both roles are not used and also causes an overlap in functionality. Since pip is a "core" Python package it also makes sense logistically to incorporate its installation into this role.

## Implementation notes ##

A sample use would be:

```yaml
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Include python
      ansible.builtin.include_role:
        name: python
        vars:
          install_pip: true
```

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Installing pip2/pip3 is incorporated into this role using role variables.
- [ ] Downstream repositories using [cisagov/ansible-role-pip] are updated to use this role with appropriate role variables.
- [ ] The [cisagov/ansible-role-pip] repository is archived.

[cisagov/ansible-role-pip]: https://github.com/cisagov/ansible-role-pip
